### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by mbarbero** [EclipseFdn/geoip-rest-api#17]
Since last deployment (July 29: https://foundation.eclipse.org/ci/webdev/job/geoip-rest-api/job/master/136/) geoip containers are being restarted on a regular basis. They are being killed with the following error message

```
Terminating due to java.lang.OutOfMemoryError: Java heap space 
```

It also show some activity spikes following a pattern:
![image](https://user-images.githubusercontent.com/452625/127625678-e82743c3-f2be-4754-b9d2-af5b5200e796.png)

There has been no code change since June 1st thought: https://github.com/EclipseFdn/geoip-rest-api

Both previous image and current image run the same java version
```
❯ docker run -it --rm --entrypoint /bin/sh eclipsefdn/geoip-rest-api:production-b51c72c-135 -c "java -version"
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (IcedTea 3.15.0) (Alpine 8.242.08-r0)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
❯ docker run -it --rm --entrypoint /bin/sh eclipsefdn/geoip-rest-api:production-b51c72c-136 -c "java -version"
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (IcedTea 3.15.0) (Alpine 8.242.08-r0)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

It does not seem to be a DoS or a service abuse. When I look at service logs on nginx for today and yesterday (excluding request from `52.157.153.85`, as it is the statuspage monitor):

```
nginx1# cat /var/log/nginx/account.eclipse.org/access.log /var/log/nginx/account.eclipse.org/access.log.1 | grep geoip | grep -v "52.157.153.85" | cut -d ' ' -f1 | sort | uniq -c
    136 172.30.206.92
    136 198.41.30.195
```

all traffic is coming from internal network. It seems that we now self DoS our service as not a single request completes

I'm able to reproduce with requests like `curl http://localhost:8080/geoip/subnets/ipv4/sy`

My guess is that maxmind DB has changed in some way and it breaks some assumptions on the app.

**Comment by autumnfound** [comment]
Checking this out, here are some small initial finds. Where 13670 is the PID of my running dev server. Since we run in JVM mode, we won't see a large jump from this number I'd think:

```
❯ ps -o rss -p 13670
  RSS
446768 (445MB)
❯ ls /tmp/mmd/db -alsh
total 102M
  0 drwxr-xr-x 2 martin martin  100 Jul 30 09:22 .
  0 drwxr-xr-x 4 martin martin   80 Jul 30 09:22 ..
13M -rw-r--r-- 1 martin martin  13M Jul 30 09:22 GeoLite2-Country-Blocks-IPv4.csv
90M -rw-r--r-- 1 martin martin  90M Jul 30 09:22 GeoLite2-Country-Blocks-IPv6.csv
12K -rw-r--r-- 1 martin martin 9.7K Jul 30 09:22 GeoLite2-Country-Locations-en.csv
❯ ls /tmp/mmd/bin -alsh
total 93M
  0 drwxr-xr-x 2 martin martin  80 Jul 30 09:22 .
  0 drwxr-xr-x 4 martin martin  80 Jul 30 09:22 ..
77M -rw-r--r-- 1 martin martin 77M Jul 26 20:15 GeoLite2-City.mmdb
16M -rw-r--r-- 1 martin martin 16M Jul 26 20:09 GeoLite2-Country.mmdb
```

Our current max for pods is 512Mi, so I'm thinking we might be operating a little too close to the top end. I'm going to look and see if I can improve that number though.

**Comment by autumnfound** [comment]
Ah. Looked into the JVM dockerfile and we set `-Xmx256`. I'm going to upgrade the image regardless. We are running on Quarkus 0.28, and most of our containers are running on the last version pre 2.x (with a 2.x upgrade in the works). There have been heaps of improvements, so I'll see what that bears out
