### ISSUE TITLE
Fix MaxMind database downloads post-CCPA update

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/geoip-rest-api#8]
There has been an update to how MaxMind manages their databases that require an account and license key to download the databases/CSVs. The update links have been updated and have broken future builds until this is fixed. Below is a link explaining the changes.

https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

**Comment by mbarbero** [comment]
This is fixed.
